name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # รันสคริปต์เฉพาะตอนที่ push โค้ดเข้า branch main (ปรับเป็น master ได้ถ้าใช้ master)

# ตั้งสิทธิ์ให้ GitHub Actions สามารถจัดการและเขียนข้อมูลลง GitHub Pages ได้
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Production
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # โฟลเดอร์ที่ Vite บิวด์เสร็จแล้วจะอยู่ที่นี่

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
